os: Visual Studio 2015
version: 0.0.{build}
clone_depth: 5
install:
- git submodule update --init --recursive
- set QTDIR=C:\Qt\5.9\msvc2015
- set PATH=%QTDIR%\bin;%PATH%
- call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat"
- nuget install -Version 1.8.0 -OutputDirectory ./3rdparty/windows rmt_libssh2
- nuget install redis-64 -excludeversion
- qmake -v
- redis-64\tools\redis-server.exe --service-install
- redis-64\tools\redis-server.exe --service-start
build_script:
- qmake CONFIG+=release DESTDIR=%cd%/build
- nmake /S /NOLOGO
test_script:
- cd tests/unit_tests
- qmake DEFINES+=INTEGRATION_TESTS DESTDIR=%cd%/bin 
- nmake /S /NOLOGO
- '%cd%/bin/tests -txt'
